services:
  app:
    build: .
    ports:
      - ${APP_PORT:-8888}:80
    env_file: .env
    volumes:
      - ./storage/app/private/downloads:/var/www/html/storage/app/private/downloads
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
  horizon:
    build: .
    command: /horizon-entrypoint.sh
    env_file: .env
    volumes:
      - ./storage/app/private/downloads:/var/www/html/storage/app/private/downloads
    depends_on:
      - redis
      - mysql
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ytdlp
      MYSQL_USER: ytdlp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - 3306:3306
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  redis_data: null
  mysql_data: null
networks: {}
